configured_endpoints: 66
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/arbi-city%2Farbi-b91e4b449d56075e07df0e35af427bf5a4aff0a5b558b133cf5cbcdd7dc7d629.yml
openapi_spec_hash: 7a13acdb1fdfc9e31c2a8ddb97dcdb61
config_hash: 1a3eace8d536da91cb75a542c4330aa2
